name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  riverpod_annotation: ^2.3.3
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather
      
dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  yumemi_lints: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
